sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t jasperkennis/aws-play -f Dockerfile.dev .

script:
  - docker run -e CI=true jasperkennis/aws-play npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "aws-play"
  env: "AwsPlay-env"
  bucket_name: "elasticbeanstalk-us-east-2-874082075030"
  bucket_path: "aws-play"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
